name: autosqflite
description: An automatic SQLite database helper for Dart/Flutter that handles table creation and schema updates automatically.
version: 1.1.0
homepage: https://github.com/keesplugandpay/autosqflite

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  sqflite_sqlcipher: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2
  integration_test:
    sdk: flutter


flutter:

