name: autosqflite
description: An automatic SQLite database helper for Dart/Flutter that handles table creation and schema updates automatically.
version: 1.0.0
homepage: https://github.com/yourusername/autosqflite

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite: ^2.3.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.2

  
flutter:

